CRM/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OgsysCRM.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int AddressId { get; set; }
        
        public virtual Address Address { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
    }
}

CRM/Models/CustomerViewModel.cs
namespace OgsysCRM.Models
{
    public class CustomerViewModel
    {
        public Customer Customer { get; set; }

        public CustomerViewModel()
        {
            Customer = new Customer();
            Customer.Id = 0;
            Customer.FirstName = "";
            Customer.LastName = "";
            Customer.CompanyName = "";
            Customer.Email = "";
            Customer.Phone = "";
            Customer.Address = new Address();
        }

        public CustomerViewModel(Customer customer)
        {
            Customer = customer;
        }
    }
}

CRM/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using OgsysCRM.DAL;
using OgsysCRM.Models;
using OgsysCRM.Infrastructure;
using OgsysCRM.Models.DataTables;
using System.Data;
using OgsysCRM.Extensions;
using OgsysCRM.Helpers;

namespace OgsysCRM.Controllers
{
    public class CustomerController : BaseController
    {
        private readonly ICustomerRepo _customerRepo;
        private readonly IAddressRepo _addressRepo;

        public CustomerController()
        {
            _customerRepo = new CustomerRepo(new AppContext());
            _addressRepo = new AddressRepo(new AppContext());
        }

        [AppAuthorize]
        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpPost]
        public JsonResult CustomerTable([ModelBinder(typeof(ModelBinderDataTableExtension))] IDataTableRequest requestModel)
        {
            requestModel.Length = requestModel.Length < Constants.MinLength ? Constants.MinLength : requestModel.Length;
            var customers = _customerRepo.GetAllCustomersForTable(requestModel.Columns.GetSortedColumns().FirstOrDefault(), requestModel.Search);

            var result = new
            {
                draw = requestModel.Draw,
                data = customers.Skip(requestModel.Start).Take(requestModel.Length).Select(x => new
                {
                    x.Id,
                    x.FirstName,
                    x.LastName,
                    x.CompanyName,
                    x.Email,
                    x.Phone,
                    x.Address
                }).ToArray().Select(x => new
                {
                    x.Id,
                    Name = x.FirstName + " " + x.LastName,
                    x.CompanyName,
                    x.Email,
                    x.Phone,
                    Address = GetAddress(x.Address)
                }),
                recordsFiltered = customers.Count(),
                recordsTotal = customers.Count()
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new CustomerViewModel();

            return View("Partials/_CustomerForm", model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var customer = _customerRepo.GetCustomerById(id);
            var model = new CustomerViewModel(customer);

            return View("Partials/_CustomerForm", model);
        }

        [HttpPost]
        public ActionResult Customer(CustomerViewModel customerViewModel)
        {
            if (customerViewModel.Customer.Id == 0)
            {
                try
                {
                    var address = customerViewModel.Customer.Address;
                    _addressRepo.InsertAddress(address);
                    _addressRepo.Save();

                    var customer = customerViewModel.Customer;
                    customer.AddressId = address.Id;
                    _customerRepo.InsertCustomer(customer);
                    _customerRepo.Save();

                    return Json(new { msg = "Customer Added!", error = false });
                }
                catch (Exception)
                {
                    return Json(new { msg = "There was an error!", error = true });
                }
            }
            else
            {
                try
                {
                    _addressRepo.UpdateAddress(customerViewModel.Customer.Address);
                    _addressRepo.Save();

                    var customer = customerViewModel.Customer;
                    _customerRepo.UpdateCustomer(customer);
                    _customerRepo.Save();

                    return Json(new { msg = "Customer Updated!", error = false });
                }
                catch (Exception)
                {
                    return Json(new { msg = "There was an error!", error = true });
                }

            }
        }
       
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var addressId = _customerRepo.GetCustomerById(id).AddressId;
                
                _customerRepo.DeleteCustomer(id);
                _customerRepo.Save();
                _addressRepo.DeleteAddress(addressId);
                _addressRepo.Save();

                return Json(new { msg = "Customer Deleted!", error = false });
            }
            catch (Exception)
            {
                return Json(new { msg = "There was an error!", error = true });
            }
        }

        #region Helper
        private string GetAddress(Address address)
        {
            var fullAddress = "";

            if (address != null)
            {
                fullAddress = address.Address1 + ", " +
                    address.City + ", " +
                    address.State + " " +
                    address.Country + " " +
                    address.Zipcode;
            }

            return fullAddress;
        }
        #endregion
    }
}

CRM/Views/Customer/Index.cshtml
@model OgsysCRM.Models.Customer

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br /><br />
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">
            Customers
            <span class="header-add-info">
                <button type="button" id="createBtn" class="btn btn-xs btn-add">
                    <span class="spinner-part"></span>
                    <span class="spinner-part"></span>
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
            </span>
            <span class="header-add-info table-search"></span>
        </h3>
    </div>
    <div class="panel-body">
        <div id="tableDiv" class="table-body " data-datatable="customerTable">
            @Html.Partial("Partials/_CustomerTable")
        </div>
    </div>
</div>

@Html.Partial("Partials/_CustomerFormModal")

<script type="text/javascript">
    $(document).ready(function () {
        DataTableHandler.handleDataTableDefaults();
        var table = $("#customerTable").DataTable({
            "ajax": {
                type: 'POST',
                url: '@Url.Action("CustomerTable", "Customer")'
            },
            "language": {
                "emptyTable": "No customers found"
            },
            "rowCallback": function (row, data) {
                $(row).on("click", function () { });
            },
            "scrollY": "500px",
            "columns": [
                { "data": "Id", "visible": false },
                { "data": "Name" },
                { "data": "CompanyName" },
                { "data": "Email" },
                { "data": "Phone", "orderable": false },
                { "data": "Address", "orderable": false },
                {
                    data: null,
                    orderable: false,
                    className: "center",
                    defaultContent: "<span class='glyphicon glyphicon-pencil'></span>"
                },
                {
                    data: null,
                    orderable: false,
                    className: "center",
                    defaultContent: "<span class='glyphicon glyphicon-remove'></span>"
                }
            ]
        }).on('preXhr.dt', function (e, settings, data) {
        });
        DataTableHandler.currentTable.setTable($("#customerTable"));

        $("#createBtn").on('click', function () {
            var resourceUrl = '@Url.Action("Create", "Customer")';
            $.get(resourceUrl, function (data) {
                var modalTemp = $('#customerModalTemplate');
                modalTemp.find('.modal-title').text("Create Customer");
                modalTemp.find('.modal-footer').find(":button").show();
                modalTemp.find('.modal-body').empty().html(data);
                modalTemp.modal('show');
            });
        });

        $("#customerTable").on('click', '.glyphicon-pencil', function (e) {
            e.preventDefault();
            var rowData = $('#customerTable').DataTable().row($(this).closest("tr")).data();
            var resourceUrl = '@Url.Action("Edit", "Customer")' + '?id=' + rowData.Id;
            $.get(resourceUrl, function (data) {
                var modalTemp = $('#customerModalTemplate');
                modalTemp.find('.modal-title').text("Edit Customer");
                modalTemp.find('.modal-footer').find(":button").show();
                modalTemp.find('.modal-body').empty().html(data);
                modalTemp.modal('show');
            });
        });

        $("#customerTable").on('click', '.glyphicon-remove', function (e) {
            e.preventDefault();
            var rowData = $('#customerTable').DataTable().row($(this).closest("tr")).data();
            var resourceUrl = '@Url.Action("Delete", "Customer")';
            bootbox.confirm("Are you sure you would like to delete this customer?", function (result) {
                if (result) {
                    $.ajax({
                        type: "POST",
                        url: resourceUrl,
                        data: { id: rowData.Id }
                    }).success(function (data) {
                        if (!data.error) {
                            DataTableHandler.currentTable.table.DataTable().ajax.reload();
                            toastr.success(data.msg, '');
                        } else if (data.error || data === 'Error') {
                            $('#errorDiv').empty().html(data).removeClass('hidden');
                            toastr.error(data.msg, '');
                        }
                    });
                }
            });

            $("#customerTable").DataTable().ajax.reload();
        });
    });
</script>

CRM/Views/Customer/NotAuthorized.cshtml
@{
    ViewBag.Title = "NotAuthorized";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br /><br />
<h2>Not Authorized</h2>
<p>You are not authorized to view this.</p>